#!/usr/bin/env ruby
# frozen_string_literal: true

require "yaml"

require "sparrow"

config = YAML.safe_load(File.read(ENV.fetch("SPARROW_CONFIG", nil)))
Sparrow::Master.new(config).start

# TODO(shouichi): Graceful shutdown on SIGTERM.
